### ISSUE TITLE
SQL migrations?

### ISSUE THREAD

**Issue by IGx89** [microsoft/durabletask-mssql#116]
What is the intended method for production apps to keep their SQL schema up-to-date when new releases with schema changes come out? The [table schema documentation](https://microsoft.github.io/durabletask-mssql/#/architecture?id=table-schema) says that the functions host automatically provisions the database upon startup, which I'm guessing involves migrations as well. That requires the app to be using a database user with full schema privileges however, which the docs further down (and every DBA :p) says to not do, instead using a low-privilege user with only the dt_runtime role. That seems to negate the previous guidance.

I looked at the schema script, schema-1.0.0.sql, and it doesn't appear to be doing anything related to schema versions. Running that script manually seems like probably the best approach in production, but if that doesn't support migrations (such as if v1.1 adds a new column to a table) then that won't work either.

**Comment by cgillum** [comment]
The plan is to support both automatic and manual schema migrations. The code for executing the schema migration can be found [here](https://github.com/microsoft/durabletask-mssql/blob/231ddd427ff4a291ccb195a6199f1bab140a7287/src/DurableTask.SqlServer/SqlDbManager.cs#L30-L121). We don't yet have documentation for this because we only planned to support schema migration after the v1.0 release, but you can expect we'll have documentation ready when it's time for the v1.1 release (or whichever release requires the first schema migration). At that point, you can expect there will also be instructions for how DBAs can do this without requiring the app to have elevated permissions.

The intended design is that we'll add new schema script files every time we do a release that involves a schema change. For example, we may add a schema-1.1.0.sql file which performs `ALTER TABLE` statements to add new columns. Existing schema files (like schema-1.0.0.sql) will remain unchanged.

**Comment by IGx89** [comment]
Perfect, thanks for the details! That gives me a lot more confidence about using this storage provider, knowing those things are being thought of and planned for.
