### ISSUE TITLE
Instance ID should be 256 char

### ISSUE THREAD

**Issue by bhugot** [microsoft/durabletask-mssql#187]
According to https://learn.microsoft.com/en-us/azure/azure-functions/durable/durable-functions-orchestrations?tabs=csharp-inproc#orchestration-identity.

**Comment by cgillum** [comment]
Ah, indeed the SQL provider limits this to 100 characters. I don't think our instance ID length checks are actually consistent across providers. I may just update the documentation the say that instance IDs generally can only be as long as 100 characters (without changing the actual behavior).

I want to avoid supporting longer instance IDs because that could hurt join performance in the case of SQL due to the larger primary key sizes.

**Comment by cgillum** [comment]
I've merged a change to the documentation which does two things:

* Reduces the max instance ID length to 100
* Adds a note that the actual enforcement of the rules may vary depending on which storage provider is used.

The doc update should be live by tomorrow.
