### ISSUE TITLE
Custom Task Hub name is ignored

### ISSUE THREAD

**Issue by scale-tone** [microsoft/durabletask-mssql#29]
Here is my host.json:

```
{
    "version": "2.0",
    "extensions": {
        "http": {
            "routePrefix": "tino"
        },
        "durableTask": {
            "hubName": "VerySpecialTaskHub",
            "storageProvider": {
                "type": "mssql",
                "connectionStringName": "SqlConnectionString",
                "taskEventLockTimeout": "00:02:00"
            }
        }
    }
}
```

And yet still everything goes into the default 'dbo' task hub:
![image](https://user-images.githubusercontent.com/5447190/120928187-e3ffcc80-c6e3-11eb-8098-af9056a8bc7f.png)

, and `VerySpecialTaskHub` never gets created. 

What am I doing wrong?

**Comment by usemam** [comment]
Hi @scale-tone ,
Which package are you using in your sample - Microsoft.DurableTask.SqlServer.AzureFunctions or Microsoft.DurableTask.SqlServer? And what version?

**Comment by scale-tone** [comment]
@usemam , I was following [these instructions](https://microsoft.github.io/durabletask-mssql/#/quickstart?id=net-core-31), so it is `Microsoft.DurableTask.SqlServer.AzureFunctions`, and its latest version - `0.9.0-beta`.
Code is [here](https://github.com/scale-tone/DurableFunctionsMonitor/tree/master/custom-backends/mssql), btw.

**Comment by bhugot** [comment]
same  for me

**Comment by usemam** [comment]
@scale-tone @bhugot 
As a work-around you can define "taskHubName" property inside "storageProvider" object in your host.json file.
Like this:
`{
    "version": "2.0",
    "extensions": {
        "http": {
            "routePrefix": "tino"
        },
        "durableTask": {
            "hubName": "VerySpecialTaskHub",
            "storageProvider": {
                "type": "mssql",
                "taskHubName": "VerySpecialTaskHub",
                "connectionStringName": "SqlConnectionString",
                "taskEventLockTimeout": "00:02:00"
            }
        }
    }
}
`

@cgillum Could you please confirm if this configuration issue is a bug?

**Comment by cgillum** [comment]
Sorry for missing this discussion. What you're seeing is by design, currently. More details here: https://microsoft.github.io/durabletask-mssql/#/taskhubs?id=configuring-task-hub-names. Long-story short, the default configuration of the SQL backend infers the task hub name from the SQL login username, though you can change this by changing a [setting in the database.

Let me know if you have any questions about this. It's one aspect of the SQL provider's design that breaks from conventions, and I'm curious to see how it works or doesn't work for various scenarios. :)

**Comment by scale-tone** [comment]
Thanks @cgillum , that explains it. I must have misread the documentation, didn't realize that automatic inference *overshadows* host.json settings.

But would't it make more sense to do it vice-versa, aka to prefer host.json's `hubName` over automatic inference? That would at least be consistent with the default storage provider's behavior...

**Comment by cgillum** [comment]
Yes, using host.json by default would have been more natural. I tried this in an earlier version but unfortunately ran into a number of experience problems for non-Azure Functions clients (KEDA, SQL Server Management Studio, etc.) since there’s no way to specify a task hub name there. The SQL provider is unique in that we’re trying to promote integration with 3rd party tools and apps, and that unfortunately makes things like task hubs a bit more complicated. Defaulting to user credentials made the setup much simpler for several of these experiences.
