### ISSUE TITLE
Durable Entities - State Storage Location

### ISSUE THREAD

**Issue by dustynlightfoot** [microsoft/durabletask-mssql#67]
Hi,

I'm testing out the new Azure SQL storage provider for Durable Functions, but I can't seem to find a table where the state of my Durable Entities is being persisted?

KR,
Dustyn

**Comment by cgillum** [comment]
You can find entities in the `[dt].[Instances]` table in your database, just like where you find orchestrations. You'll know it's an entity because the `InstanceID` value starts with `@`.

```sql
SELECT TOP (10) [TaskHub], [Name], [InstanceID], [CreatedTime], [LastUpdatedTime]
FROM [DurableDB].[dt].[Instances]
WHERE [Name] = 'counter'
```
![image](https://user-images.githubusercontent.com/2704139/149997597-f48d06f9-7b49-4b98-a706-336f54aa269f.png)

**Comment by dustynlightfoot** [comment]
Hey @cgillum ,

Thanks very much for your response.
Ah I see now, Instance has an InputPayloadId field which relates to the Payloads table where I can find the current state of the entity in the Text field.

**Comment by cgillum** [comment]
Ah, yes, sorry, I didn't realize it was the state payload you were looking for, otherwise I would have shared a query that included this. Looks like you found it on your own, though. :)
